# TensorFlow Tensors: From Zero to Hero
## Day 1 - Interactive Exploration

### **Instructions**:
1. Run each section sequentially
2. Modify values and re-run to see changes
3. Uncomment the EXPERIMENT lines to explore
4. Pay attention to shapes - they're crucial!

In [1]:
import tensorflow as tf
import numpy as np
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")

TensorFlow version: 2.20.0
GPU Available: []


In [2]:
# ============================================
# PART 1: What Even Is a Tensor?
# ============================================

In [3]:
print("\n" + "="*50)
print("PART 1: Creating Tensors")
print("="*50)


PART 1: Creating Tensors


`tensorflow.constant()`
Creates a constant tensor from a tensor-like object.

```python
tf.constant(
    value, dtype=None, shape=None, name='Const'
) -> Union[tf.Operation, ops._EagerTensorBase]
```



In [4]:
# A scalar (0D tensor) - just a single number
scalar = tf.constant(42)
print(f"\nScalar: {scalar}")
print(f"Shape: {scalar.shape}")
print(f"Rank (dimensions): {scalar.ndim}")


Scalar: 42
Shape: ()
Rank (dimensions): 0


A scalar (OD tensor) has no shape, no dimension

In [5]:
# A vector (1D tensor) - like a list
vector = tf.constant([1, 2, 3, 4, 5])
print(f"\nVector: {vector}")
print(f"Shape: {vector.shape}")
print(f"Rank: {vector.ndim}")


Vector: [1 2 3 4 5]
Shape: (5,)
Rank: 1


In [6]:
# A matrix (2D tensor) - your comfort zone from ML!
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Shape: {matrix.shape}")  # (rows, columns)
print(f"Rank: {matrix.ndim}")


Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Rank: 2


In [7]:
# A 3D tensor - think of it as a "stack of matrices"
# Shape: (depth, rows, columns)
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
print(f"\n3D Tensor:\n{tensor_3d}")
print(f"Shape: {tensor_3d.shape}")
print(f"Rank: {tensor_3d.ndim}")


3D Tensor:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape: (3, 2, 2)
Rank: 3


In [8]:
# EXPERIMENT: Create a 4D tensor (batch of images!)

tensor_4d = tf.constant([[[[1, 2, 3]]]])
print(f"\n4D Tensor shape: {tensor_4d.shape}")


4D Tensor shape: (1, 1, 1, 3)


In [9]:
# ============================================
# PART 2: TensorFlow vs NumPy - The Showdown
# ============================================

In [10]:
print("\n" + "="*50)
print("PART 2: TensorFlow vs NumPy")
print("="*50)


PART 2: TensorFlow vs NumPy


In [11]:
# Create the same data in both
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tf_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print(f"\nNumPy array:\n{np_array}")
print(f"TensorFlow tensor:\n{tf_tensor}")


NumPy array:
[[1 2 3]
 [4 5 6]]
TensorFlow tensor:
[[1 2 3]
 [4 5 6]]


In [12]:
# They look the same! So what's different?

In [13]:
# 1. Easy conversion between them
converted_to_np = tf_tensor.numpy()
converted_to_tf = tf.constant(np_array)
print(f"\nTensor to NumPy: {type(converted_to_np)}")
print(f"NumPy to Tensor: {type(converted_to_tf)}")


Tensor to NumPy: <class 'numpy.ndarray'>
NumPy to Tensor: <class 'tensorflow.python.framework.ops.EagerTensor'>


### `tensor.numpy()`

#### What .numpy() does internally:

```python
# When you call tensor.numpy()
tf_tensor = tf.constant([[1, 2], [3, 4]])
np_array = tf_tensor.numpy()

# Behind the scenes:
# 1. TF checks if tensor is on GPU or CPU
# 2. If GPU → copies data to CPU memory (this can be slow!)
# 3. Creates a NumPy array that shares the same memory buffer (zero-copy when on CPU)
# 4. Returns the NumPy view
```

#### Key Insights:
- **On CPU**: `.numpy()` is nearly free – it's just a different "view" of the same data
- **On GPU**: There's a copy operation (GPU → CPU), which can be a bottleneck
- **Eager execution** (default in TF 2.x) makes this seamless – in TF 1.x, this was much harder!

In [14]:
# 2. Operations are similar
print(f"\nNumPy addition: {np_array + 10}")
print(f"TensorFlow addition: {tf_tensor + 10}")


NumPy addition: [[11 12 13]
 [14 15 16]]
TensorFlow addition: [[11 12 13]
 [14 15 16]]


In [15]:
# 3. But TensorFlow has GPU acceleration!
# This is the superpower - same code, faster execution

In [20]:
# ============================================
# PART 3: Tensor Operations - Getting Practical
# ============================================

In [21]:
print("\n" + "="*50)
print("PART 3: Essential Tensor Operations")
print("="*50)


PART 3: Essential Tensor Operations


In [22]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

In [23]:
# Element-wise operations (just like NumPy!)
print(f"\nAddition:\n{a + b}")
print(f"\nMultiplication (element-wise):\n{a * b}")
print(f"\nSquare:\n{tf.square(a)}")


Addition:
[[ 6  8]
 [10 12]]

Multiplication (element-wise):
[[ 5 12]
 [21 32]]

Square:
[[ 1  4]
 [ 9 16]]


In [24]:
# Matrix multiplication (the real MVP for neural networks!)

print(f"\nMatrix multiplication (a @ b):\n{tf.matmul(a, b)}")


Matrix multiplication (a @ b):
[[19 22]
 [43 50]]


In [30]:
# Reshaping - you'll do this A LOT
original = tf.constant([1, 2, 3, 4, 5, 6])
print(original)
print(f"\nOriginal shape: {original.shape}")

reshaped = tf.reshape(original, (2, 3))
print(f"Reshaped to (2, 3):\n{reshaped}")

reshaped2 = tf.reshape(original, (3, 2))
print(f"Reshaped to (3, 2):\n{reshaped2}")

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

Original shape: (6,)
Reshaped to (2, 3):
[[1 2 3]
 [4 5 6]]
Reshaped to (3, 2):
[[1 2]
 [3 4]
 [5 6]]


In [26]:
# EXPERIMENT: What happens if you try to reshape to incompatible shape?
# Uncomment to see error:
bad_reshape = tf.reshape(original, (2, 2))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 6 values, but the requested shape has 4 [Op:Reshape]

In [34]:
# ============================================
# PART 4: Indexing & Slicing - NumPy Skills Transfer!
# ============================================

In [35]:
print("\n" + "="*50)
print("PART 4: Indexing & Slicing")
print("="*50)


PART 4: Indexing & Slicing


In [36]:
tensor = tf.constant([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

print(f"\nOriginal tensor:\n{tensor}")
print(f"\nFirst row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Element at [1, 2]: {tensor[1, 2]}")
print(f"Bottom right 2x2:\n{tensor[1:, 2:]}")


Original tensor:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
First column: [1 5 9]
Element at [1, 2]: 7
Bottom right 2x2:
[[ 7  8]
 [11 12]]


In [38]:
# EXPERIMENT: Try different slicing patterns
print(tensor[::2, :])  # Every other row
print(tensor[:, 1:3])  # Columns 1 and 2

tf.Tensor(
[[ 1  2  3  4]
 [ 9 10 11 12]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [39]:
# ============================================
# PART 5: Data Types Matter!
# ============================================

In [40]:
print("\n" + "="*50)
print("PART 5: Data Types")
print("="*50)


PART 5: Data Types


In [41]:
# Default is int32 for integers
int_tensor = tf.constant([1, 2, 3])
print(f"\nInteger tensor dtype: {int_tensor.dtype}")


Integer tensor dtype: <dtype: 'int32'>


In [42]:
# Default is float32 for floats (neural networks love float32!)
float_tensor = tf.constant([1.0, 2.0, 3.0])
print(f"Float tensor dtype: {float_tensor.dtype}")

Float tensor dtype: <dtype: 'float32'>


In [43]:
# You can specify dtype explicitly
explicit_float = tf.constant([1, 2, 3], dtype=tf.float32)
print(f"Explicit float32: {explicit_float}")

Explicit float32: [1. 2. 3.]


In [44]:
# Converting between types
converted = tf.cast(int_tensor, dtype=tf.float32)
print(f"Converted to float32: {converted}")

Converted to float32: [1. 2. 3.]


In [45]:
# ============================================
# PART 6: Random Tensors - Neural Network Weights!
# ============================================

In [46]:
print("\n" + "="*50)
print("PART 6: Random Tensors")
print("="*50)


PART 6: Random Tensors


In [48]:
# This is how neural network weights are initialized!
random_normal = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
print(f"\nRandom normal (mean=0, std=1):\n{random_normal}")


Random normal (mean=0, std=1):
[[ 1.4865453   0.05518418  0.58583254]
 [ 0.28936753 -0.79604477  0.7007    ]
 [ 0.8971697   0.05917929  0.86513233]]


In [49]:
random_uniform = tf.random.uniform(shape=(2, 4), minval=0, maxval=10)
print(f"\nRandom uniform [0, 10):\n{random_uniform}")


Random uniform [0, 10):
[[3.5894406 6.8676176 7.414504  5.2513146]
 [1.703651  3.9064455 5.976447  4.2455378]]


### Normal Distribution vs. Uniform Distribution

**Normal Distribution**
Normal distribution is a continuous probability distribution that is symmetric about the mean, depicting that data near the mean are more frequent in occurrence than data far from the mean.
It has a `bell shaped curve`.

![Normal Distribution](https://media.geeksforgeeks.org/wp-content/uploads/20250606125317822107/a_normal_distribution1.webp "Normal Distribution")

**Uniform Distribution**
A Uniform Distribution is a type of probability distribution which always gives constant output to an input function in a given period (say, (a,b)).

It is also known as rectangular distribution (continuous uniform distribution).
It has two parameters a and b: a = minimum and b = maximum. The distribution is written as U (a, b).
It has a `rectangular curve`.

![Uniform Distribution](https://media.geeksforgeeks.org/wp-content/uploads/20240603172506/uniform-distribution.webp "Uniform Distribution")

In [51]:
# Set seed for reproducibility
tf.random.set_seed(42)
reproducible = tf.random.normal(shape=(2, 2))
print(f"\nReproducible random:\n{reproducible}")


Reproducible random:
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]]


In [52]:
# ============================================
# PART 7: Aggregation Operations
# ============================================

In [53]:
print("\n" + "="*50)
print("PART 7: Aggregation")
print("="*50)


PART 7: Aggregation


In [54]:
values = tf.constant([[1.0, 2.0, 3.0],
                     [4.0, 5.0, 6.0]])

In [55]:
print(f"\nOriginal:\n{values}")
print(f"Sum of all: {tf.reduce_sum(values)}")
print(f"Mean of all: {tf.reduce_mean(values)}")
print(f"Max: {tf.reduce_max(values)}")
print(f"Min: {tf.reduce_min(values)}")


Original:
[[1. 2. 3.]
 [4. 5. 6.]]
Sum of all: 21.0
Mean of all: 3.5
Max: 6.0
Min: 1.0


In [56]:
# Sum along specific axis
print(f"\nSum along axis 0 (columns): {tf.reduce_sum(values, axis=0)}")
print(f"Sum along axis 1 (rows): {tf.reduce_sum(values, axis=1)}")


Sum along axis 0 (columns): [5. 7. 9.]
Sum along axis 1 (rows): [ 6. 15.]


In [57]:
# ============================================
# CHALLENGE: Mini Practice!
# ============================================

In [58]:
print("\n" + "="*50)
print("CHALLENGE TIME!")
print("="*50)


CHALLENGE TIME!


In [59]:
print("""
Try these exercises:

1. Create a 5x5 matrix with random values between 0 and 1
2. Extract the middle 3x3 portion
3. Calculate the mean of that portion
4. Reshape the original 5x5 into a vector of 25 elements

""")


Try these exercises:

1. Create a 5x5 matrix with random values between 0 and 1
2. Extract the middle 3x3 portion
3. Calculate the mean of that portion
4. Reshape the original 5x5 into a vector of 25 elements




In [62]:
# 1. 
tf.random.set_seed(42)
rand_matrix = tf.random.uniform(shape=(5,5), minval=0, maxval=1)
print(f"5x5 matrix with random values between 0 and 1: \n\n{rand_matrix}")

5x5 matrix with random values between 0 and 1: 

[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041]
 [0.68467236 0.74011743 0.8724445  0.22632635 0.22319686]
 [0.3103881  0.7223358  0.13318717 0.5480639  0.5746088 ]
 [0.8996835  0.00946367 0.5212307  0.6345445  0.1993283 ]
 [0.72942245 0.54583454 0.10756552 0.6767061  0.6602763 ]]


In [65]:
# 2. 
middle_3x3 = rand_matrix[1:4, 1:4]
print(f"middle_3x3 slicing: \n\n{middle_3x3}")

middle_3x3 slicing: 

[[0.74011743 0.8724445  0.22632635]
 [0.7223358  0.13318717 0.5480639 ]
 [0.00946367 0.5212307  0.6345445 ]]


In [ ]:
# 3. 
print(f"Mean of middle 3x3 matrix = {tf.reduce_mean(middle_3x3)}")

Mean of middle 3x3 matrix = 0.48974597454071045


In [74]:
# 4. 
print(f"Reshaped to vector: \n{tf.reshape(rand_matrix, shape=(25, ))}")
print(f"\nReshaped to vector shape: {tf.reshape(rand_matrix, shape=(25, )).shape}")

Reshaped to vector: 
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763 ]

Reshaped to vector shape: (25,)


In [75]:
print("\n" + "="*50)
print("🎉 You've completed Tensor Basics!")
print("="*50)
print("""
Key Takeaways:
1. Tensors are multi-dimensional arrays (0D to nD)
2. TensorFlow ≈ NumPy + GPU acceleration + automatic differentiation
3. Shapes are CRUCIAL - always check tensor.shape
4. Operations are similar to NumPy (your existing knowledge transfers!)
5. Random tensors initialize neural network weights

Next: We'll use these tensors to build a neural network from scratch!
""")


🎉 You've completed Tensor Basics!

Key Takeaways:
1. Tensors are multi-dimensional arrays (0D to nD)
2. TensorFlow ≈ NumPy + GPU acceleration + automatic differentiation
3. Shapes are CRUCIAL - always check tensor.shape
4. Operations are similar to NumPy (your existing knowledge transfers!)
5. Random tensors initialize neural network weights

Next: We'll use these tensors to build a neural network from scratch!

